# Generated by Django 5.2.6 on 2025-10-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_booking_status_alter_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter')], default='Renter', max_length=10),
        ),
    ]
