# Generated by Django 5.2.6 on 2025-10-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_booking_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Renter', 'Renter')], default='Renter', max_length=10),
        ),
    ]
