# Generated by Django 5.2.6 on 2025-10-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_remove_booking_user_type_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
